### ISSUE TITLE
Mobile navigation menu hard to close

### ISSUE THREAD

**Issue by benabbottnz** [SomethingNew71/classicminidiy#299]
The GIF below shows a mobile view opening the navigation and then struggling to close it. I have the same experience on my real iPhone SE 2020.

![Recording 2023-06-06 at 14 25 58](https://github.com/SomethingNew71/classicminidiy/assets/2616473/1db2a012-aea3-4e32-9ad0-4b9dc83e6c2b)

**Comment by SomethingNew71** [comment]
@benabbottnz thanks for identifying this! I have it fixed in the newest build and it should be live on your device now. :-)
