### ISSUE TITLE
Error 525 - SSL handshake failed

### ISSUE THREAD

**Issue by leewaa** [SomethingNew71/classicminidiy#68]
I was simply trying to access the webpage at https://www.classicminidiy.com/  

A picture speaks a thousand words:
![image](https://user-images.githubusercontent.com/5164431/37624893-2a32b89c-2bca-11e8-9836-ed3e9296f024.png)

**Comment by SomethingNew71** [comment]
Thanks for the heads up. 

Looks like my SSL redirect isn't working. It appears regular HTTP is working.  

- [http://www.classicminidiy.com/](http://www.classicminidiy.com/)

I will figure out the issue with my DNS settings.

**Comment by SomethingNew71** [comment]
Fixed in the recent release. Thank you @leewaa for calling this out.
